import type { Exercise, LeaderboardEntry, TrackerState } from "./types";
import { expandedExercises } from "./catalog";
import {
  commentSeed,
  communitySeed,
  friendRequestSeed,
  gymSeed,
  liftSeed,
  messageSeed,
  messageThreadSeed,
  notificationSeed,
  profileSeed
} from "./platformData";

const exercises: Exercise[] = [
  ["barbell-bench", "Barbell Bench Press", "Chest", ["Triceps", "Shoulders"], "Barbell", "Horizontal Push"],
  ["incline-bench", "Incline Bench Press", "Chest", ["Shoulders", "Triceps"], "Barbell", "Horizontal Push"],
  ["db-bench", "Dumbbell Bench Press", "Chest", ["Triceps"], "Dumbbells", "Horizontal Push"],
  ["machine-chest", "Machine Chest Press", "Chest", ["Triceps"], "Machine", "Horizontal Push"],
  ["cable-fly", "Cable Fly", "Chest", ["Shoulders"], "Cable", "Isolation"],
  ["pec-deck", "Pec Deck", "Chest", [], "Machine", "Isolation"],
  ["back-squat", "Back Squat", "Quads", ["Glutes", "Core"], "Barbell", "Squat"],
  ["front-squat", "Front Squat", "Quads", ["Glutes", "Core"], "Barbell", "Squat"],
  ["leg-press", "Leg Press", "Quads", ["Glutes"], "Machine", "Squat"],
  ["hack-squat", "Hack Squat", "Quads", ["Glutes"], "Machine", "Squat"],
  ["leg-extension", "Leg Extension", "Quads", [], "Machine", "Isolation"],
  ["deadlift", "Conventional Deadlift", "Full Body", ["Hamstrings", "Back", "Glutes"], "Barbell", "Hinge"],
  ["rdl", "Romanian Deadlift", "Hamstrings", ["Glutes", "Back"], "Barbell", "Hinge"],
  ["leg-curl", "Lying Leg Curl", "Hamstrings", [], "Machine", "Isolation"],
  ["hip-thrust", "Barbell Hip Thrust", "Glutes", ["Hamstrings"], "Barbell", "Hinge"],
  ["lat-pulldown", "Lat Pulldown", "Back", ["Biceps"], "Cable", "Vertical Pull"],
  ["pull-up", "Pull-Up", "Back", ["Biceps"], "Bodyweight", "Vertical Pull"],
  ["barbell-row", "Barbell Row", "Back", ["Biceps"], "Barbell", "Horizontal Pull"],
  ["seated-row", "Seated Cable Row", "Back", ["Biceps"], "Cable", "Horizontal Pull"],
  ["ohp", "Overhead Press", "Shoulders", ["Triceps"], "Barbell", "Vertical Push"],
  ["lateral-raise", "Dumbbell Lateral Raise", "Shoulders", [], "Dumbbells", "Isolation"],
  ["face-pull", "Cable Face Pull", "Shoulders", ["Back"], "Cable", "Isolation"],
  ["barbell-curl", "Barbell Curl", "Arms", ["Biceps"], "Barbell", "Isolation"],
  ["db-curl", "Dumbbell Curl", "Arms", ["Biceps"], "Dumbbells", "Isolation"],
  ["tricep-pushdown", "Tricep Pushdown", "Arms", ["Triceps"], "Cable", "Isolation"],
  ["dip", "Dip", "Arms", ["Chest", "Triceps"], "Bodyweight", "Vertical Push"],
  ["cable-crunch", "Cable Crunch", "Core", [], "Cable", "Core"],
  ["plank", "Plank", "Core", [], "Bodyweight", "Core", "Time"]
].map(([id, name, bodyPart, secondaryMuscles, equipment, movementType, trackingType = "Weight + Reps"]) => ({
  id: id as string,
  name: name as string,
  bodyPart: bodyPart as string,
  secondaryMuscles: secondaryMuscles as string[],
  equipment: equipment as string,
  movementType: movementType as string,
  trackingType: trackingType as Exercise["trackingType"]
}));

const planId = "plan-strength";
const phaseId = "phase-base";
const week1 = "week-1";
const week2 = "week-2";
const pushSession = "session-push";
const pullSession = "session-pull";
const legsSession = "session-legs";

export const seedState: TrackerState = {
  version: 3,
  plans: [
    {
      id: planId,
      name: "Strength Foundation",
      goal: "Build strength across the main compound lifts",
      notes: "Three-day strength split",
      createdAt: new Date().toISOString(),
      isActive: true
    }
  ],
  phases: [
    {
      id: phaseId,
      planId,
      name: "Base Phase",
      order: 0,
      goal: "Build quality volume",
      durationWeeks: 2
    }
  ],
  weeks: [
    { id: week1, planId, phaseId, weekNumber: 1, title: "Week 1", notes: "" },
    { id: week2, planId, phaseId, weekNumber: 2, title: "Week 2", notes: "" }
  ],
  sessions: [
    { id: pushSession, weekId: week1, day: "Monday", name: "Push", order: 0, notes: "" },
    { id: pullSession, weekId: week1, day: "Wednesday", name: "Pull", order: 1, notes: "" },
    { id: legsSession, weekId: week1, day: "Friday", name: "Legs", order: 2, notes: "" },
    { id: "session-push-2", weekId: week2, day: "Monday", name: "Push", order: 0, notes: "" },
    { id: "session-pull-2", weekId: week2, day: "Wednesday", name: "Pull", order: 1, notes: "" },
    { id: "session-legs-2", weekId: week2, day: "Friday", name: "Legs", order: 2, notes: "" }
  ],
  prescriptions: [
    ["p-bench", pushSession, "barbell-bench", "Barbell Bench Press", "Chest", "Barbell", 3, "6-8", 180, 0],
    ["p-ohp", pushSession, "ohp", "Overhead Press", "Shoulders", "Barbell", 3, "6-8", 150, 1],
    ["p-pulldown", pullSession, "lat-pulldown", "Lat Pulldown", "Back", "Cable", 3, "8-12", 120, 0],
    ["p-row", pullSession, "barbell-row", "Barbell Row", "Back", "Barbell", 3, "6-8", 150, 1],
    ["p-squat", legsSession, "back-squat", "Back Squat", "Quads", "Barbell", 3, "6-8", 180, 0],
    ["p-rdl", legsSession, "rdl", "Romanian Deadlift", "Hamstrings", "Barbell", 3, "8-10", 150, 1],
    ["p-bench-2", "session-push-2", "barbell-bench", "Barbell Bench Press", "Chest", "Barbell", 3, "6-8", 180, 0],
    ["p-pull-2", "session-pull-2", "lat-pulldown", "Lat Pulldown", "Back", "Cable", 3, "8-12", 120, 0],
    ["p-squat-2", "session-legs-2", "back-squat", "Back Squat", "Quads", "Barbell", 3, "6-8", 180, 0]
  ].map(([id, sessionId, exerciseId, exerciseName, bodyPart, equipment, sets, reps, restSeconds, order]) => ({
    id: id as string,
    sessionId: sessionId as string,
    exerciseId: exerciseId as string,
    exerciseName: exerciseName as string,
    bodyPart: bodyPart as string,
    equipment: equipment as string,
    sets: sets as number,
    reps: reps as string,
    restSeconds: restSeconds as number,
    order: order as number,
    notes: ""
  })),
  setLogs: [],
  completedWorkouts: [],
  exercises: [
    ...exercises.map((exercise) => ({ ...exercise, bodyRegions: [exercise.bodyPart], searchAliases: [] })),
    ...expandedExercises.filter((exercise) => !exercises.some((existing) => existing.name === exercise.name))
  ],
  bodyweight: [
    { id: "bw-1", recordedAt: "2026-06-01T12:00:00.000Z", weight: 184.5 },
    { id: "bw-2", recordedAt: "2026-06-08T12:00:00.000Z", weight: 183.8 },
    { id: "bw-3", recordedAt: "2026-06-15T12:00:00.000Z", weight: 183.2 }
  ],
  activePlanId: planId,
  activeWorkout: null,
  currentUserId: "user-robert",
  profiles: profileSeed,
  gyms: gymSeed,
  joinedGymIds: ["gym-south-beach"],
  liftSubmissions: liftSeed,
  workoutFeedback: [],
  communityPosts: communitySeed,
  comments: commentSeed,
  friendRequests: friendRequestSeed,
  messageThreads: messageThreadSeed,
  messages: messageSeed,
  messageReports: [],
  notifications: notificationSeed
};

export const leaderboardSeed: LeaderboardEntry[] = [
  {
    id: "lb-01",
    rank: 1,
    rankChange: 2,
    athlete: "Evan Cole",
    handle: "@evancole",
    gym: "Crunch Fitness - South Beach",
    city: "Miami Beach",
    state: "Florida",
    exercise: "Conventional Deadlift",
    rankingType: "Absolute",
    score: 585,
    verification: "Competition Verified",
    bodyweight: 218,
    total: 1475,
    ageGroup: "30-34",
    experienceLevel: "Advanced"
  },
  {
    id: "lb-02",
    rank: 3,
    rankChange: 1,
    athlete: "Mia Santos",
    handle: "@miastrong",
    gym: "Crunch Fitness - Brickell",
    city: "Miami",
    state: "Florida",
    exercise: "Back Squat",
    rankingType: "Absolute",
    score: 525,
    verification: "Moderator Verified",
    bodyweight: 154,
    total: 1335,
    ageGroup: "25-29",
    experienceLevel: "Advanced"
  },
  {
    id: "lb-03",
    rank: 5,
    rankChange: -1,
    athlete: "Robert J.",
    handle: "@rjrob23",
    gym: "Crunch Fitness - South Beach",
    city: "Miami Beach",
    state: "Florida",
    exercise: "Barbell Bench Press",
    rankingType: "Absolute",
    score: 495,
    verification: "Moderator Verified",
    bodyweight: 210,
    total: 1015,
    ageGroup: "30-34",
    experienceLevel: "Advanced",
    isCurrentUser: true
  },
  {
    id: "lb-13",
    rank: 4,
    rankChange: 3,
    athlete: "Marcus Bell",
    handle: "@mbellstrong",
    gym: "Crunch Fitness - Coral Springs",
    city: "Coral Springs",
    state: "Florida",
    exercise: "Back Squat",
    rankingType: "Absolute",
    score: 505,
    verification: "Video Submitted",
    bodyweight: 198,
    total: 1290,
    ageGroup: "30-34",
    experienceLevel: "Advanced"
  },
  {
    id: "lb-14",
    rank: 6,
    rankChange: 2,
    athlete: "Nico Rivera",
    handle: "@nicorivera",
    gym: "Crunch Fitness - South Beach",
    city: "Miami Beach",
    state: "Florida",
    exercise: "Back Squat",
    rankingType: "Absolute",
    score: 485,
    verification: "Community Verified",
    bodyweight: 187,
    total: 1185,
    ageGroup: "25-29",
    experienceLevel: "Intermediate"
  },
  {
    id: "lb-15",
    rank: 7,
    rankChange: -2,
    athlete: "Talia Brooks",
    handle: "@taliabrooks",
    gym: "Crunch Fitness - Tampa Palms",
    city: "Tampa",
    state: "Florida",
    exercise: "Back Squat",
    rankingType: "Absolute",
    score: 455,
    verification: "Moderator Verified",
    bodyweight: 168,
    total: 1110,
    ageGroup: "35-39",
    experienceLevel: "Advanced"
  },
  {
    id: "lb-16",
    rank: 8,
    rankChange: 4,
    athlete: "Chris Velez",
    handle: "@chrisvelez",
    gym: "Crunch Fitness - Brickell",
    city: "Miami",
    state: "Florida",
    exercise: "Back Squat",
    rankingType: "Absolute",
    score: 435,
    verification: "Self Reported",
    bodyweight: 176,
    total: 1055,
    ageGroup: "20-24",
    experienceLevel: "Intermediate"
  },
  {
    id: "lb-17",
    rank: 9,
    rankChange: 1,
    athlete: "Sofia Martin",
    handle: "@sofiamartin",
    gym: "Crunch Fitness - Winter Park",
    city: "Winter Park",
    state: "Florida",
    exercise: "Barbell Bench Press",
    rankingType: "Absolute",
    score: 315,
    verification: "Competition Verified",
    bodyweight: 142,
    total: 875,
    ageGroup: "20-24",
    experienceLevel: "Veteran"
  },
  {
    id: "lb-18",
    rank: 2,
    rankChange: 5,
    athlete: "Darius King",
    handle: "@dariusking",
    gym: "Crunch Fitness - Weston",
    city: "Weston",
    state: "Florida",
    exercise: "Conventional Deadlift",
    rankingType: "Absolute",
    score: 565,
    verification: "Video Submitted",
    bodyweight: 242,
    total: 1395,
    ageGroup: "40-44",
    experienceLevel: "Advanced"
  },
  {
    id: "lb-19",
    rank: 10,
    rankChange: -3,
    athlete: "Jalen Woods",
    handle: "@jalenwoods",
    gym: "Crunch Fitness - St. Petersburg",
    city: "St. Petersburg",
    state: "Florida",
    exercise: "Overhead Press",
    rankingType: "Absolute",
    score: 255,
    verification: "Community Verified",
    bodyweight: 191,
    total: 995,
    ageGroup: "30-34",
    experienceLevel: "Intermediate"
  },
  {
    id: "lb-04",
    rank: 1,
    rankChange: 4,
    athlete: "Kayla Nguyen",
    handle: "@kaylarunspr",
    gym: "Crunch Fitness - Winter Park",
    city: "Winter Park",
    state: "Florida",
    exercise: "Bench Press",
    rankingType: "Pound-for-pound",
    score: 4.82,
    verification: "Competition Verified",
    bodyweight: 128,
    total: 1025,
    ageGroup: "20-24",
    experienceLevel: "Veteran"
  },
  {
    id: "lb-05",
    rank: 2,
    rankChange: 1,
    athlete: "Robert J.",
    handle: "@rjrob23",
    gym: "Crunch Fitness - South Beach",
    city: "Miami Beach",
    state: "Florida",
    exercise: "Deadlift",
    rankingType: "Pound-for-pound",
    score: 4.73,
    verification: "Moderator Verified",
    bodyweight: 210,
    total: 1015,
    ageGroup: "30-34",
    experienceLevel: "Advanced",
    isCurrentUser: true
  },
  {
    id: "lb-20",
    rank: 3,
    rankChange: 6,
    athlete: "Elena Ortiz",
    handle: "@elenaortiz",
    gym: "Crunch Fitness - Brickell",
    city: "Miami",
    state: "Florida",
    exercise: "Back Squat",
    rankingType: "Pound-for-pound",
    score: 4.36,
    verification: "Community Verified",
    bodyweight: 139,
    total: 890,
    ageGroup: "25-29",
    experienceLevel: "Intermediate"
  },
  {
    id: "lb-21",
    rank: 4,
    rankChange: -1,
    athlete: "Sam Patel",
    handle: "@sampatel",
    gym: "Crunch Fitness - South Beach",
    city: "Miami Beach",
    state: "Florida",
    exercise: "Barbell Bench Press",
    rankingType: "Pound-for-pound",
    score: 4.12,
    verification: "Self Reported",
    bodyweight: 165,
    total: 845,
    ageGroup: "30-34",
    experienceLevel: "Novice"
  },
  {
    id: "lb-06",
    rank: 5,
    rankChange: 3,
    athlete: "Jordan Price",
    handle: "@jordanpress",
    gym: "Crunch Fitness - Tampa Palms",
    city: "Tampa",
    state: "Florida",
    exercise: "Overhead Press",
    rankingType: "Pound-for-pound",
    score: 4.41,
    verification: "Video Submitted",
    bodyweight: 183,
    total: 905,
    ageGroup: "35-39",
    experienceLevel: "Intermediate"
  },
  {
    id: "lb-07",
    rank: 1,
    rankChange: 2,
    athlete: "Andre Brooks",
    handle: "@andrebrooks",
    gym: "Crunch Fitness - Coral Springs",
    city: "Coral Springs",
    state: "Florida",
    exercise: "Powerlifting Total",
    rankingType: "Total",
    score: 1575,
    verification: "Competition Verified",
    bodyweight: 231,
    total: 1575,
    ageGroup: "35-39",
    experienceLevel: "Veteran"
  },
  {
    id: "lb-08",
    rank: 2,
    rankChange: -1,
    athlete: "Mia Santos",
    handle: "@miastrong",
    gym: "Crunch Fitness - Brickell",
    city: "Miami",
    state: "Florida",
    exercise: "Powerlifting Total",
    rankingType: "Total",
    score: 1335,
    verification: "Moderator Verified",
    bodyweight: 154,
    total: 1335,
    ageGroup: "25-29",
    experienceLevel: "Advanced"
  },
  {
    id: "lb-22",
    rank: 3,
    rankChange: 3,
    athlete: "Loren Hayes",
    handle: "@lorenhayes",
    gym: "Crunch Fitness - Tampa Palms",
    city: "Tampa",
    state: "Florida",
    exercise: "Powerlifting Total",
    rankingType: "Total",
    score: 1285,
    verification: "Video Submitted",
    bodyweight: 202,
    total: 1285,
    ageGroup: "30-34",
    experienceLevel: "Advanced"
  },
  {
    id: "lb-23",
    rank: 4,
    rankChange: 1,
    athlete: "Priya Shah",
    handle: "@priyashah",
    gym: "Crunch Fitness - Winter Park",
    city: "Winter Park",
    state: "Florida",
    exercise: "Powerlifting Total",
    rankingType: "Total",
    score: 1115,
    verification: "Community Verified",
    bodyweight: 151,
    total: 1115,
    ageGroup: "35-39",
    experienceLevel: "Intermediate"
  },
  {
    id: "lb-09",
    rank: 1,
    rankChange: 5,
    athlete: "Dylan Reed",
    handle: "@dylanreid",
    gym: "Crunch Fitness - St. Petersburg",
    city: "St. Petersburg",
    state: "Florida",
    exercise: "Relative Total",
    rankingType: "Relative total",
    score: 6.21,
    verification: "Competition Verified",
    bodyweight: 148,
    total: 920,
    ageGroup: "20-24",
    experienceLevel: "Novice"
  },
  {
    id: "lb-10",
    rank: 2,
    rankChange: 2,
    athlete: "Robert J.",
    handle: "@rjrob23",
    gym: "Crunch Fitness - South Beach",
    city: "Miami Beach",
    state: "Florida",
    exercise: "Relative Total",
    rankingType: "Relative total",
    score: 4.83,
    verification: "Moderator Verified",
    bodyweight: 210,
    total: 1015,
    ageGroup: "30-34",
    experienceLevel: "Advanced",
    isCurrentUser: true
  },
  {
    id: "lb-24",
    rank: 3,
    rankChange: 4,
    athlete: "Cam Ellis",
    handle: "@camellis",
    gym: "Crunch Fitness - Coral Springs",
    city: "Coral Springs",
    state: "Florida",
    exercise: "Relative Total",
    rankingType: "Relative total",
    score: 4.58,
    verification: "Video Submitted",
    bodyweight: 181,
    total: 1025,
    ageGroup: "25-29",
    experienceLevel: "Advanced"
  },
  {
    id: "lb-25",
    rank: 4,
    rankChange: -2,
    athlete: "Bria Fox",
    handle: "@briafox",
    gym: "Crunch Fitness - Weston",
    city: "Weston",
    state: "Florida",
    exercise: "Relative Total",
    rankingType: "Relative total",
    score: 4.02,
    verification: "Self Reported",
    bodyweight: 156,
    total: 820,
    ageGroup: "20-24",
    experienceLevel: "Novice"
  },
  {
    id: "lb-11",
    rank: 1,
    rankChange: 9,
    athlete: "Avery King",
    handle: "@averyking",
    gym: "Crunch Fitness - Weston",
    city: "Weston",
    state: "Florida",
    exercise: "Best PR Jump",
    rankingType: "Most improved",
    score: 18,
    verification: "Community Verified",
    bodyweight: 169,
    total: 1125,
    ageGroup: "25-29",
    experienceLevel: "Intermediate"
  },
  {
    id: "lb-12",
    rank: 2,
    rankChange: 7,
    athlete: "Robert J.",
    handle: "@rjrob23",
    gym: "Crunch Fitness - South Beach",
    city: "Miami Beach",
    state: "Florida",
    exercise: "Best PR Jump",
    rankingType: "Most improved",
    score: 14,
    verification: "Moderator Verified",
    bodyweight: 210,
    total: 1015,
    ageGroup: "30-34",
    experienceLevel: "Advanced",
    isCurrentUser: true
  },
  {
    id: "lb-26",
    rank: 3,
    rankChange: 5,
    athlete: "Isaac Stone",
    handle: "@isaacstone",
    gym: "Crunch Fitness - Brickell",
    city: "Miami",
    state: "Florida",
    exercise: "Best PR Jump",
    rankingType: "Most improved",
    score: 12,
    verification: "Video Submitted",
    bodyweight: 196,
    total: 1085,
    ageGroup: "35-39",
    experienceLevel: "Intermediate"
  },
  {
    id: "lb-27",
    rank: 4,
    rankChange: 2,
    athlete: "Maya Chen",
    handle: "@mayachen",
    gym: "Crunch Fitness - Tampa Palms",
    city: "Tampa",
    state: "Florida",
    exercise: "Best PR Jump",
    rankingType: "Most improved",
    score: 9,
    verification: "Self Reported",
    bodyweight: 132,
    total: 705,
    ageGroup: "20-24",
    experienceLevel: "Novice"
  }
];
